import type { Review } from './types';

/** Pool of clearly fictional reviewer identities used across the catalogue. */
const R = {
  maya: { author: 'Maya Okonkwo', location: 'Lisbon, PT' },
  dev: { author: 'Devin Alvarez', location: 'Austin, US' },
  yuki: { author: 'Yuki Tanaka', location: 'Osaka, JP' },
  sam: { author: 'Sam Whitfield', location: 'Manchester, UK' },
  priya: { author: 'Priya Raman', location: 'Bengaluru, IN' },
  leo: { author: 'Leo Bertrand', location: 'Lyon, FR' },
  ines: { author: 'Ines Duarte', location: 'Porto, PT' },
  tom: { author: 'Tom Halvorsen', location: 'Oslo, NO' },
  zara: { author: 'Zara Haddad', location: 'Amman, JO' },
  nico: { author: 'Nico Fontaine', location: 'Lille, FR' },
  ela: { author: 'Ela Kaya', location: 'Izmir, TR' },
  ravi: { author: 'Ravi Menon', location: 'Kochi, IN' },
};

export const reviews: Record<string, Review[]> = {
  'air-pro': [
    {
      ...R.maya,
      id: 'air-pro-1',
      rating: 5,
      title: 'The commute finally sounds like a studio',
      body: 'I take a 45-minute train ride twice a week. The ANC here is the first pair that handles low rumble without the pressure headache others gave me. Bass is deep but never smeared, and transparency mode is genuinely usable — I can order coffee without taking them off.',
      date: '2025-11-18',
      verified: true,
      variant: 'Midnight Graphite',
    },
    {
      ...R.dev,
      id: 'air-pro-2',
      rating: 5,
      title: 'Battery is understated and reliable',
      body: 'I charge them Monday and they last the full week with about four hours of ANC playback left on Thursday. The case adds three more full charges. I have never once had them die mid-trip.',
      date: '2025-10-02',
      verified: true,
      variant: 'Midnight Graphite',
    },
    {
      ...R.yuki,
      id: 'air-pro-3',
      rating: 4,
      title: 'Superb, but the case is not pocket-sized',
      body: 'Sound deserves five stars — the mids in particular are beautifully clear for vocals. I only docked one because the case is a little tall for a jeans pocket, so I keep the headphones on a hook instead. Worth it regardless.',
      date: '2025-09-21',
      verified: true,
    },
    {
      ...R.sam,
      id: 'air-pro-4',
      rating: 5,
      title: 'Replaced three pairs of much pricier cans',
      body: 'Had a flagship pair that started crackling at the cable. These just work, and they fold flat into a bag without a case. Multipoint switching between laptop and phone is flawless.',
      date: '2025-08-14',
      verified: true,
    },
  ],
  mini: [
    {
      ...R.priya,
      id: 'mini-1',
      rating: 5,
      title: 'Tiny, and the sound is not',
      body: 'I honestly cannot tell these apart from my old wired pair at half the volume. Fit is secure through a full gym session — no falling out, no pressure points. The wing tips are the right size too, which is rarer than it should be.',
      date: '2025-11-06',
      verified: true,
      variant: 'Pearl White',
    },
    {
      ...R.leo,
      id: 'mini-2',
      rating: 4,
      title: 'Excellent daily driver',
      body: 'Six hours per charge and the case adds three cycles, so I charge once a week. Only note is that the default EQ is quite warm — there is a preset toggle in the app that fixes it in two taps.',
      date: '2025-10-11',
      verified: true,
    },
    {
      ...R.ines,
      id: 'mini-3',
      rating: 5,
      title: 'Survived a monsoon in Singapore',
      body: 'Got caught in a proper downpour cycling home. Rinsed the buds under the tap, dried them, and they have been fine since. Call quality in a windy street was good too — my partner said I sounded clear.',
      date: '2025-07-29',
      verified: true,
    },
  ],
  'watch-one': [
    {
      ...R.tom,
      id: 'watch-one-1',
      rating: 5,
      title: 'Six days without a charger trip',
      body: 'I travel for work constantly and the biggest win here is the battery. Six full days with always-on display, continuous heart rate and sleep tracking enabled. The screen is bright enough in direct sun and the always-on mode is not a battery criminal.',
      date: '2025-12-01',
      verified: true,
      variant: 'Slate Titanium',
    },
    {
      ...R.zara,
      id: 'watch-one-2',
      rating: 5,
      title: 'Sleep data that is actually readable',
      body: 'Most trackers give me a wall of graphs. This one gives me a single sentence each morning. That is exactly what I wanted. HRV trend has been genuinely useful for training load too.',
      date: '2025-11-12',
      verified: true,
    },
    {
      ...R.nico,
      id: 'watch-one-3',
      rating: 4,
      title: 'Great watch, small ecosystem',
      body: 'Build quality is excellent and it survived a 2-metre pool dive without complaint. There just are not many third-party apps yet. If you want a mature app store, this is not it — if you want a good watch, it is.',
      date: '2025-09-08',
      verified: true,
    },
  ],
  'home-hub': [
    {
      ...R.ela,
      id: 'home-hub-1',
      rating: 5,
      title: 'Everything works offline',
      body: 'The selling point for me was local control. Lights, locks, blinds and sensors all run without the cloud. I pulled the internet cable for a weekend as a test and the house kept working perfectly. That sold me.',
      date: '2025-10-27',
      verified: true,
    },
    {
      ...R.ravi,
      id: 'home-hub-2',
      rating: 5,
      title: 'Set up in nine minutes',
      body: 'Scanned a QR, named four rooms, done. Adding devices after that is a matter of holding one button. The dashboard is calm and quick, unlike my previous hub which took a weekend.',
      date: '2025-09-30',
      verified: true,
    },
    {
      ...R.sam,
      id: 'home-hub-3',
      rating: 4,
      title: 'Rock solid, fan is very quiet',
      body: 'Been running non-stop for four months with zero dropouts. Fanless design means it is literally silent. Only wish the ethernet port were Gigabit — I run a lot of local video.',
      date: '2025-08-19',
      verified: true,
    },
  ],
  'soundbar-x': [
    {
      ...R.maya,
      id: 'soundbar-x-1',
      rating: 5,
      title: 'Dialogue finally intelligible at low volume',
      body: 'This is a soundbar for people who watch things at 11pm. The dialogue lift is doing a lot of work — I no longer turn it up to 60% to follow a whispered line. Bass is deep for a bar this slim.',
      date: '2025-11-25',
      verified: true,
    },
    {
      ...R.dev,
      id: 'soundbar-x-2',
      rating: 5,
      title: 'One cable, zero fuss',
      body: 'HDMI eARC took care of audio and control, and the wireless sub paired automatically on first power-on. My partner is not technical and she set it up in about two minutes.',
      date: '2025-10-19',
      verified: true,
    },
    {
      ...R.yuki,
      id: 'soundbar-x-3',
      rating: 4,
      title: 'Great sound, plan your cable route',
      body: 'Soundstage is wide and imaging is precise. It comes with a wall bracket but you will want to plan cable routing first. Mounted mine and hid everything in a raceway.',
      date: '2025-08-27',
      verified: true,
    },
  ],
  'portable-speaker': [
    {
      ...R.leo,
      id: 'portable-speaker-1',
      rating: 5,
      title: 'Thrown in a bag, survived two seasons',
      body: 'It lives in the side pocket of my hiking pack now. Scratched, dented, still sounds like day one. The strap is genuinely strong and the IP rating is not just marketing — it has been rained on repeatedly.',
      date: '2025-11-09',
      verified: true,
      variant: 'Ember Orange',
    },
    {
      ...R.ines,
      id: 'portable-speaker-2',
      rating: 5,
      title: 'Pairs into stereo, and it works',
      body: 'I have two of these in the kitchen and the stereo pair has real separation. Plenty loud for a patio dinner for eight people with the battery at half.',
      date: '2025-09-15',
      verified: true,
    },
    {
      ...R.priya,
      id: 'portable-speaker-3',
      rating: 4,
      title: 'Lovely, no app needed',
      body: 'The physical controls are a relief — no phone required to change volume. Small gripe is that the pairing button is easy to hit by accident inside a bag.',
      date: '2025-07-22',
      verified: true,
    },
  ],
  'powerbank-20k': [
    {
      ...R.tom,
      id: 'powerbank-20k-1',
      rating: 5,
      title: 'Four full phone charges, small enough to forget',
      body: '20000mAh in a body slimmer than my old 10000mAh pack. Charged my phone from 10% to 100% three times with change left. The digital percentage readout is accurate to within a point or two.',
      date: '2025-12-05',
      verified: true,
    },
    {
      ...R.zara,
      id: 'powerbank-20k-2',
      rating: 5,
      title: 'Charges my laptop',
      body: 'The 100W USB-C port negotiated with my work laptop without complaint and topped up 40% while I worked through a layover. That alone justifies the price.',
      date: '2025-10-22',
      verified: true,
    },
    {
      ...R.nico,
      id: 'powerbank-20k-3',
      rating: 4,
      title: 'Excellent, but check airline rules at 20000mAh',
      body: 'Great product, and the fault is mine for not reading the airline rules. Under 100Wh so it is fine in most places, but check your carrier. Support confirmed over chat in under a minute.',
      date: '2025-09-04',
      verified: true,
    },
  ],
  'smart-lamp': [
    {
      ...R.ela,
      id: 'smart-lamp-1',
      rating: 5,
      title: 'Circadian mode is not a gimmick',
      body: 'It ramps from warm amber at 9pm to neutral daylight at 8am, matching my actual schedule. I stopped the 3pm headache I used to get every day within a week.',
      date: '2025-11-14',
      verified: true,
    },
    {
      ...R.ravi,
      id: 'smart-lamp-2',
      rating: 4,
      title: 'Beautiful, works with the hub',
      body: 'The aluminium base feels substantial and the diffuser has no visible LED dots. Pairs straight to the Home Hub over Matter with no extra hub needed.',
      date: '2025-10-08',
      verified: true,
    },
  ],
  'mechanical-keyboard': [
    {
      ...R.sam,
      id: 'keyboard-1',
      rating: 5,
      title: 'Deep, clean, no hollow rattle',
      body: 'Most metal-top boards sound like a trash can on every keypress. This one has a low, muted thock with a gasket mount and a silicone layer. The stabilisers are factory-lubed and genuinely need no further work.',
      date: '2025-12-08',
      verified: true,
      variant: 'Graphite',
    },
    {
      ...R.dev,
      id: 'keyboard-2',
      rating: 5,
      title: 'Hot-swappable and easy to build up',
      body: 'Pulled the keycaps and lubed the switches in twenty minutes. The south-facing sockets mean shine-through legends line up perfectly with north-facing Cherry profile caps. Tri-mode connects to all three of my machines.',
      date: '2025-11-01',
      verified: true,
    },
    {
      ...R.maya,
      id: 'keyboard-3',
      rating: 4,
      title: 'Great board, heavy',
      body: 'The build quality is impeccable and it does not flex or ping at all. It is 1.6kg though, so it is a desktop keyboard, not a laptop companion. Worth knowing before ordering.',
      date: '2025-09-26',
      verified: true,
    },
  ],
  'wireless-mouse': [
    {
      ...R.yuki,
      id: 'mouse-1',
      rating: 5,
      title: '70 days on a charge',
      body: 'I charged it in January and it lasted through February and most of March. The sensor tracks perfectly on glass and on a cloth mat with no surface switch needed.',
      date: '2025-11-27',
      verified: true,
    },
    {
      ...R.leo,
      id: 'mouse-2',
      rating: 4,
      title: 'Very good, buttons are stiff at first',
      body: 'Clicks feel deliberate and the scroll wheel has real detents. It took about a week for the main buttons to break in, and now they are smooth. The shape suits claw grip more than fingertip.',
      date: '2025-10-14',
      verified: true,
    },
  ],
  'usb-c-hub': [
    {
      ...R.ines,
      id: 'usb-c-hub-1',
      rating: 5,
      title: 'Solved my two-port laptop',
      body: 'Two USB-C ports on my machine and I need five things. This gives me dual 4K output, gigabit ethernet, HDMI and SD, all over one cable. Runs cool under sustained 4K streaming.',
      date: '2025-12-02',
      verified: true,
    },
    {
      ...R.ravi,
      id: 'usb-c-hub-2',
      rating: 5,
      title: 'Compact and genuinely pocketable',
      body: 'Smaller than my wallet and the attached cable is long enough to reach. The aluminium shell matches my laptop finish almost perfectly.',
      date: '2025-11-03',
      verified: true,
    },
  ],
  'charging-station': [
    {
      ...R.zara,
      id: 'charging-station-1',
      rating: 5,
      title: 'Cleared the whole nightstand',
      body: 'Six devices, six cables, now zero. Everything sits on one slab and charges at full speed. The fabric top does not scratch screens, which my old stand did constantly.',
      date: '2025-11-21',
      verified: true,
      variant: 'Charcoal',
    },
    {
      ...R.tom,
      id: 'charging-station-2',
      rating: 4,
      title: 'Great organisation, needs a wall outlet nearby',
      body: 'The weighted base is genuinely stable and looks far more expensive than it is. It is a desk-and-nightstand unit rather than a travel one, so plan your cable run.',
      date: '2025-10-30',
      verified: true,
    },
  ],
};
